datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hello
    username: postgres

endpoints:
  all:
    # For local development
    sensitive: false

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

micronaut:
  application:
    name: hello-world

tracing:
  jaeger:
    enabled: true
