datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hello
    username: postgres

endpoints:
  all:
    # Makes all the endpoints available without authentication. A terrible idea in production, but
    # great when you're just exploring the framework locally.
    sensitive: false

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

micronaut:
  application:
    name: hello-micronaut

tracing:
  jaeger:
    enabled: true
